-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 11:00:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Listatelefonica` DEFAULT CHARACTER SET utf8 ;
USE `Listatelefonica` ;

-- -----------------------------------------------------
-- Table `mydb`.`contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Listatelefonica`.`contatos` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `nomeContato` VARCHAR(45) NOT NULL,
  `telefoneContato` VARCHAR(11) NOT NULL,
  `cidadeContato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
